apiVersion: v1
data:
  init.sql: |-
    \c counter-db

    CREATE TABLE IF NOT EXISTS balances (
        user_id INT PRIMARY KEY,
        balance DECIMAL(12,2) DEFAULT 0.00
    );

    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO counteruser;
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: counter-db
  name: counter-db-cm0
