apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: counter-service
  name: counter-service
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: counter-service
  template:
    metadata:
      labels:
        io.kompose.service: counter-service
    spec:
      containers:
          - name: counter-service
            image: counter-service
            imagePullPolicy: IfNotPresent
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: counter-db-secret
                    key: DATABASE_URL
              - name: HAZELCAST_URL
                valueFrom:
                  configMapKeyRef:
                    name: hazelcast-config
                    key: HAZELCAST_URL
      restartPolicy: Always
