apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: counter-db
  name: counter-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: counter-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: counter-db
    spec:
      containers:
        # - env:
        #     - name: POSTGRES_DB
        #       value: counter-db
        #     - name: POSTGRES_PASSWORD
        #       value: "12345"
        #     - name: POSTGRES_USER
        #       value: counteruser
          image: postgres:15-alpine
          livenessProbe:
            exec:
              command:
                - pg_isready -U counteruser -d counter-db
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: counter-db
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "1073741824"
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: counter-db-cm0
              readOnly: true
              subPath: init.sql
            - mountPath: /var/lib/postgresql/data
              name: counter-data
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: init.sql
                path: init.sql
            name: counter-db-cm0
          name: counter-db-cm0
        - name: counter-data
          persistentVolumeClaim:
            claimName: counter-data
