apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: counter-service
  name: counter-service
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: counter-service
  template:
    metadata:
      labels:
        io.kompose.service: counter-service
    spec:
      containers:
          - name: counter-service
            image: counter-service
            imagePullPolicy: IfNotPresent
      restartPolicy: Always
